name: ci

on:
  push:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 3
  NODE_VERSION: 16

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # v3.5.1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: yarn install --frozen-lockfile
    - run: yarn test

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # v3.5.1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - run: yarn build-storybook
